version: '2'

services:

  postgres:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=apm
      - POSTGRES_PASSWORD=apm

  kafka:
    build:
      context: .
      dockerfile: ./compose/kafka/Dockerfile
    command: /startKafka.sh
    env_file:
    - .env

  spark:
    build:
      context: .
      dockerfile: ./compose/spark/Dockerfile
    command: /startSpark.sh
    env_file:
      - .env
    volumes:
    - .:/app
    - ~/.sbt:/root/.sbt
    - ~/.ivy2:/root/.ivy2
    depends_on:
      - kafka
      - -postgress
